"""Create D1 UPDATE statements with FAIR scores from an existing Owl4u CSV.

This is the one-time bridge for deployments whose WiseOwl scores were exported
before FAIR scoring was added.  Future ``export_phase`` runs include the FAIR
columns directly in ``d1_data.sql``.

Usage:
    python batch/backfill_fair.py data/run_v1_1_1/exports/ontology_results_full.csv
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import owl4_fair as fair


def sql(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def update_statement(record: dict) -> str:
    result = fair.assess_record(record)
    principles = result["principles"]
    values = {
        "fair_score": result["score"],
        "fair_findable": principles["F"]["score"],
        "fair_accessible": principles["A"]["score"],
        "fair_interoperable": principles["I"]["score"],
        "fair_reusable": principles["R"]["score"],
        "fair_credits": result["credits"],
        "fair_max_credits": result["max_credits"],
        "fair_version": result["version"],
        "fair_assessment_json": fair.compact_json(result),
    }
    assignments = ", ".join(f"{key} = {sql(value)}" for key, value in values.items())
    return (f"UPDATE ontology_scores SET {assignments} WHERE provider = {sql(record.get('provider') or 'bioportal')} "
            f"AND acronym = {sql(record['acronym'])};")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=Path, help="ontology_results_full.csv from an earlier Owl4u export")
    parser.add_argument("--output", type=Path, help="output SQL file (default: fair_backfill.sql beside the CSV)")
    args = parser.parse_args()
    output = args.output or args.csv.with_name("fair_backfill.sql")

    lines = ["-- Generated by batch/backfill_fair.py; run d1_migrate_fair.sql first."]
    with args.csv.open(newline="", encoding="utf-8-sig") as handle:
        for record in csv.DictReader(handle):
            if record.get("acronym"):
                lines.append(update_statement(record))
    output.parent.mkdir(parents=True, exist_ok=True)
    temp = output.with_suffix(output.suffix + ".tmp")
    temp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    temp.replace(output)
    print(f"Wrote {len(lines) - 1} FAIR score updates to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
